baseURL: "https://akshat4112.github.io/"
title: Akshat Gupta
#paginate: 5
theme: PaperMod
googleAnalytics: "G-8YC2E5MW2M"

# Environment-specific settings
# Hugo will use these settings when running in development (local) mode
# You can override these with CLI parameters
development:
  baseURL: "http://localhost:1313/"
  googleAnalytics: ""  # Disable analytics in development

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true

minify:
  disableXML: true
  minifyOutput: true

menu:
  main:
    - name: Posts
      url: posts
      weight: 5
    - name: Publications
      url: publications/
      weight: 10
#    - name: Search
#      url: search/
#      weight: 10
    - name: Talks
      url: talks/
      weight: 15
    - name: Events
      url: events/
      weight: 20
    - name: About
      url: about/
      weight: 25
    - name: CV
      url: https://drive.google.com/file/d/1Qj6kaZXM40ixUgOAewhZlTj57piWERSw/view?usp=drive_link
      weight: 25

params:
  math: true
  comments: true
  env: production

  profileMode:
    enabled: true
    title: "Akshat Gupta" # optional default will be site title
    subtitle: "Machine Learning Engineer | Generative AI | Diffusion Models | LLMs"
    imageUrl: "../assets/akshat_gupta.jpg" # optional
    imageTitle: "Akshat Gupta" # optional
    imageWidth: 120 # custom size
    imageHeight: 120 # custom size

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

#Params:
#  ShowReadingTime: true
#  ShowPostNavLinks: true

#    buttons:
#      - name: About
#        url: "/archive"

  socialIcons: # optional
    - name: "linkedin"
      url: "https://www.linkedin.com/in/akshat-rg/"
    - name: "github"
      url: "https://github.com/akshat4112"
    - name: "twitter"
      url: "https://twitter.com/akshat_rg"
    - name: "kaggle"
      url: "https://kaggle.com/akshat4112/"

outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search


